name: demo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  sqflite: any
  path: any
  get_cli: ^1.7.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  json_annotation: ^4.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

